
# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.9-slim

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Install pip requirements
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY ./src .
COPY ./data .

# Expose the port Streamlit runs on
EXPOSE 8501

# Run Streamlit on container startup
CMD ["streamlit", "run", "streamlit_app.py"]
